apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ckad
spec:
  hostNetwork: true
  containers:
  - name: nginx
    image: nginx:1.17.10
    ports:
    - containerPort: 80
    env:
    - name: DB_URL
      value: postgresql://mydb:5432
    - name: DB_USER_NAME
      value: admin
