apiVersion: v1
kind: Pod
metadata:
  name: loop
  namespace: ckad
spec:
  hostNetwork: true
  containers:
  - command: ["/bin/bash"]
    args: ['for i in {1..10}; do echo "Welcome $i times"; done; ']
    name: loop
    image: busybox
    ports:
    - containerPort: 80
  restartPolicy: Never

