apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: loop2
  name: loop2
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - for i in {1..10}; do echo "Welcome $i times"; done;
    image: busybox
    name: loop2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
