# we are defining 4 pods here - red-frontend, green-backend, red-backend, blue-backend

apiVersion: v1
kind: Pod
metadata:
  name: red-frontend
  namespace: rnd    # declare namespace in metadata
  labels:           # labels mapping in metadata
    color: red
    tier: frontend
  annotations:      # Example annotation
    Lab: Kubernetes Pod Design for Application Developers
spec:
  containers:
    - image: httpd:2.4.38
      name: web-server
---
apiVersion: v1
kind: Pod
metadata:
  name: green-frontend
  namespace: rnd
  labels:
    color: green
    tier: frontend
spec:
  containers:
    - image: httpd:2.4.38
      name: web-server
---
apiVersion: v1
kind: Pod
metadata:
  name: red-backend
  namespace: rnd
  labels:
    color: red
    tier: backend
spec:
  containers:
    - image: postgres:11.2-alpine
      name: db
---
apiVersion: v1
kind: Pod
metadata:
  name: blue-backend
  namespace: rnd
  labels:
    color: blue
    tier: backend
spec:
  containers:
    - image: postgres:11.2-alpine
      name: db

###################################################################################################
# Commands to try:
# 01. kubectl get pods -L color,tier  -> the -L or --label-columns displays columns for both labels
# 02. kubectl get pods -L color,tier -l color -> selects all the pods with a color label
# 03. kubectl get pods -L color,tier -l 'color=red' -> selects all the pods with color = red
# 04. kubectl get pods -L color,tier -l 'color=red,tier!=frontend' -> self explanatory
# 05. kubectl get pods -L color,tier -l 'color in (blue,green)' -> self explanatory
# 06. kubectl get pods -L color,tier -l '!color' -> selects all pods that do not have a color label.
# 07. kubectl describe pod red-backend | grep -C 2 Labels -> displays the labels for this pod.
# 08. kubectl get pods --show-labels -> will display the pods along with labels
# 09. kubectl label pod red-frontend region=APAC -> adds a new label
# 10. kubectl label pod red-frontend region=US --overwrite -> will update the label on the pod
# 11. kubectl label pod red-frontend region- -> will remove the label on the pod
# 08. kubectl describe pod red-backend | grep Annotations
###################################################################################################